"""app.py - the Prompt Lab: the test bed for the Foundry Exercises.

You do not edit this file. Each Codio guide page opens one challenge of this page
(/challenge/1, /2, /3). The student writes a system prompt or a user prompt in the
page, presses Run, and the page sends the prompt to the student's own memphis-copilot
deployment with the challenge's test messages and shows what came back. For challenge 3
it also checks every reply's JSON. It does not grade: the Check button on the guide page
does that, reading the same prompts this page saves.

Where the prompts live: prompts/challenge_<id>.json in the workspace, written on every
keystroke pause and on every Run, so the Check button and a reopened page both see the
latest text. The endpoint and key come from the .env file in the workspace root and are
re-read on every request, so a fix to .env needs no restart.

lab.sh starts and stops it. It listens on port 5000.
"""
import json
import logging
import os
import time
from pathlib import Path

import flask.cli
from flask import Flask, jsonify, redirect, render_template, request

flask.cli.show_server_banner = lambda *args, **kwargs: None
logging.getLogger("werkzeug").setLevel(logging.ERROR)

app = Flask(__name__)
app.config["TEMPLATES_AUTO_RELOAD"] = True

BASE_DIR = Path(__file__).resolve().parent
PROMPTS_DIR = BASE_DIR / "prompts"
ENV_FILE = BASE_DIR / ".env"
DEPLOYMENT = "memphis-copilot"      # the deployment name every request carries, not the model's name
PORT = int(os.environ.get("PORT", "5000"))

with open(BASE_DIR / "challenges.json", encoding="utf-8") as fh:
    _config = json.load(fh)
PASS_SCORE = _config.get("pass_score", 70)
CHALLENGES = {c["id"]: c for c in _config["challenges"]}


# ---------------------------------------------------------------------------
# Credentials: read from .env on every request
# ---------------------------------------------------------------------------
def read_env() -> dict:
    values = {}
    if ENV_FILE.is_file():
        for line in ENV_FILE.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            values[k.strip()] = v.strip().strip('"').strip("'")
    return values


def missing_config(env: dict) -> list:
    missing = [k for k in ("AI901_ENDPOINT", "AI901_KEY") if not env.get(k)]
    ep = env.get("AI901_ENDPOINT", "")
    if ep and (not ep.startswith("https://") or not ep.endswith("/")):
        missing.append("AI901_ENDPOINT (must start with https:// and end with a slash)")
    return missing


def get_client(env: dict):
    from openai import OpenAI
    return OpenAI(base_url=f"{env['AI901_ENDPOINT']}openai/v1/", api_key=env["AI901_KEY"])


def call_model(client, messages) -> str:
    response = client.chat.completions.create(model=DEPLOYMENT, messages=messages)
    return response.choices[0].message.content or ""


def classify(text: str) -> str:
    """One sentence the student can act on, for an error from the service."""
    if "401" in text or "403" in text or "AuthenticationError" in text or "PermissionDenied" in text:
        return "The endpoint refused the key (HTTP 401/403). Check AI901_KEY in .env against the portal's detail panel, and that the endpoint ends with a slash."
    if "404" in text or "NotFound" in text:
        return f"No deployment named {DEPLOYMENT} answered (HTTP 404). Check Build > Deployments in the portal; the Set up your endpoint page says how to make one."
    if "429" in text or "RateLimit" in text:
        return "The deployment is rate-limited right now (HTTP 429). Wait 60 seconds and press Run again."
    if "APIConnectionError" in text or "getaddrinfo" in text or "Name or service not known" in text:
        return "The endpoint could not be reached. Check AI901_ENDPOINT in .env against the portal."
    return "The request failed. The message below says why."


# ---------------------------------------------------------------------------
# Saved prompts: what the Check button grades
# ---------------------------------------------------------------------------
def prompt_path(challenge_id: int) -> Path:
    return PROMPTS_DIR / f"challenge_{challenge_id}.json"


def load_prompts(challenge_id: int) -> dict:
    path = prompt_path(challenge_id)
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            return {"system": str(data.get("system") or ""), "user": str(data.get("user") or "")}
        except (OSError, json.JSONDecodeError, AttributeError):
            pass
    starter = CHALLENGES[challenge_id].get("starter_user_prompt", "")
    return {"system": "", "user": starter}


def save_prompts(challenge_id: int, system_prompt: str, user_prompt: str) -> None:
    PROMPTS_DIR.mkdir(exist_ok=True)
    prompt_path(challenge_id).write_text(json.dumps({
        "challenge_id": challenge_id,
        "system": system_prompt,
        "user": user_prompt,
        "saved_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    }, indent=2), encoding="utf-8")


# ---------------------------------------------------------------------------
# Running the prompts (the same shape the grader runs)
# ---------------------------------------------------------------------------
def run_student_prompts(client, challenge: dict, system_prompt: str, user_prompt: str) -> list:
    write = challenge["write"]
    transcripts = []
    if write == ["system"]:
        for test_message in challenge["test_messages"]:
            reply = call_model(client, [{"role": "system", "content": system_prompt},
                                        {"role": "user", "content": test_message}])
            transcripts.append({"label": "Test message", "user": test_message, "assistant": reply})
        return transcripts
    if write == ["user"]:
        reply = call_model(client, [{"role": "system", "content": challenge["fixed_system_prompt"]},
                                    {"role": "user", "content": user_prompt}])
        transcripts.append({"label": "Your user prompt", "user": user_prompt, "assistant": reply})
        return transcripts
    for attachment in challenge.get("attachments", []):
        full = f"{user_prompt}\n\n--- Customer message ---\n{attachment['text']}"
        reply = call_model(client, [{"role": "system", "content": system_prompt},
                                    {"role": "user", "content": full}])
        transcripts.append({"label": attachment.get("label", ""), "user": attachment["text"], "assistant": reply})
    return transcripts


def extract_json(text: str):
    try:
        return json.loads(text)
    except (json.JSONDecodeError, TypeError):
        pass
    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end > start:
        try:
            return json.loads(text[start:end + 1])
        except json.JSONDecodeError:
            pass
    return None


def check_field_values(challenge: dict, parsed: dict):
    rules = challenge.get("field_rules") or {}
    blank, invalid = [], []
    for key, rule in rules.items():
        if key not in parsed:
            continue
        value = parsed[key]
        if value is None:
            continue
        if rule.get("type") == "string" and not isinstance(value, str):
            invalid.append(f"{key}: expected text, got {type(value).__name__} ({json.dumps(value)})")
            continue
        if isinstance(value, str) and not value.strip():
            blank.append(key)
            continue
        allowed = rule.get("allowed")
        if allowed and isinstance(value, str) and value.strip().lower() not in allowed:
            invalid.append(f"{key}: \"{value}\" is not one of {'/'.join(allowed)}")
    return blank, invalid


def check_one_reply(challenge: dict, required: list, reply: str) -> dict:
    strictly_valid = True
    try:
        parsed = json.loads(reply.strip())
    except json.JSONDecodeError:
        strictly_valid = False
        parsed = extract_json(reply)
    if not isinstance(parsed, dict):
        return {"reply_is_valid_json": False, "reply_is_json_only": False, "missing_keys": required,
                "extra_keys": [], "blank_fields": [], "invalid_values": []}
    blank, invalid = check_field_values(challenge, parsed)
    return {"reply_is_valid_json": True, "reply_is_json_only": strictly_valid,
            "missing_keys": [k for k in required if k not in parsed],
            "extra_keys": [k for k in parsed if k not in required],
            "blank_fields": blank, "invalid_values": invalid}


def check_output_format(challenge: dict, transcripts: list):
    required = challenge.get("json_keys")
    if not required:
        return None
    checks = []
    for t in transcripts:
        result = check_one_reply(challenge, required, t["assistant"])
        result["label"] = t.get("label", "")
        checks.append(result)
    return {"required_keys": required, "checks": checks}


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.route("/")
def index():
    return redirect("/challenge/1")


@app.route("/challenge/<int:challenge_id>")
def challenge_page(challenge_id):
    if challenge_id not in CHALLENGES:
        return redirect("/challenge/1")
    return render_template("index.html", challenge_id=challenge_id)


@app.route("/api/health")
def health():
    env = read_env()
    missing = missing_config(env)
    return jsonify({"configured": not missing, "missing": missing, "deployment": DEPLOYMENT,
                    "pass_score": PASS_SCORE})


@app.route("/api/challenges")
def challenges():
    return jsonify({"pass_score": PASS_SCORE, "challenges": _config["challenges"]})


@app.route("/api/prompts/<int:challenge_id>", methods=["GET", "POST"])
def prompts(challenge_id):
    if challenge_id not in CHALLENGES:
        return jsonify({"error": "no such challenge"}), 404
    if request.method == "POST":
        data = request.get_json(silent=True) or {}
        save_prompts(challenge_id, str(data.get("system_prompt") or ""), str(data.get("user_prompt") or ""))
        return jsonify({"saved": True})
    return jsonify(load_prompts(challenge_id))


@app.route("/api/run", methods=["POST"])
def run():
    data = request.get_json(silent=True) or {}
    try:
        challenge = CHALLENGES[int(data.get("challenge_id"))]
    except (KeyError, TypeError, ValueError):
        return jsonify({"error": "no such challenge"}), 400
    system_prompt = str(data.get("system_prompt") or "")
    user_prompt = str(data.get("user_prompt") or "")
    save_prompts(challenge["id"], system_prompt, user_prompt)

    needed = [("system prompt", system_prompt, "system"), ("user prompt", user_prompt, "user")]
    for name, value, side in needed:
        if side in challenge["write"] and not value.strip():
            return jsonify({"error": f"Write your {name} first - the editor is empty."}), 400

    env = read_env()
    missing = missing_config(env)
    if missing:
        return jsonify({"error": "Your .env file is not complete: " + ", ".join(missing)
                                 + ". Fill it in on the Set up your endpoint page, save, and press Run again."}), 400
    started = time.perf_counter()
    try:
        client = get_client(env)
        transcripts = run_student_prompts(client, challenge, system_prompt, user_prompt)
    except Exception as exc:  # noqa: BLE001
        text = f"{type(exc).__name__}: {exc}".replace(env.get("AI901_KEY", "\x00"), "[key hidden]")
        return jsonify({"error": classify(text), "detail": text[-600:]}), 502
    return jsonify({
        "challenge_id": challenge["id"],
        "transcripts": transcripts,
        "format_check": check_output_format(challenge, transcripts),
        "elapsed_s": round(time.perf_counter() - started, 1),
        "saved": True,
    })


if __name__ == "__main__":
    # host="0.0.0.0" so Codio can reach the app through the box URL; one request at a time.
    app.run(host="0.0.0.0", port=PORT, debug=False, use_reloader=False, threaded=False)
