#!/usr/bin/env bash
# lab.sh - start, stop or check the Prompt Lab (app.py), the test bed for this assignment.
#
#   bash lab.sh start     start it (does nothing if it is already running)
#   bash lab.sh stop      stop it
#   bash lab.sh restart   stop it, then start it again
#   bash lab.sh status    say whether it is running
#   bash lab.sh prepare   install the assignment's libraries ahead of the first start
#
# The guide runs these for you: the Set up your endpoint page runs prepare, the Start the
# Prompt Lab page runs start. The server's own output goes to .testbed.log, so this
# terminal stays readable. You do not edit this file.

cd "$(dirname "$0")" || exit 1

PORT="${PORT:-5000}"
PIDFILE=".testbed.pid"
LOGFILE=".testbed.log"

port_open() {
  python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:${PORT}/api/health', timeout=2)" \
    >/dev/null 2>&1
}

is_running() {
  { [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null; } || port_open
}

ensure_packages() {
  # The course stack should ship openai and python-dotenv; Flask is never in the
  # stack. Install whatever is missing once per box, for this user only, and say so
  # plainly if that fails.
  missing=""
  python3 -c "import flask" >/dev/null 2>&1   || missing="$missing Flask>=3.0,<4.0"
  python3 -c "import dotenv" >/dev/null 2>&1  || missing="$missing python-dotenv>=1.0"
  python3 -c "import openai" >/dev/null 2>&1  || missing="$missing openai>=1.60"
  if [ -z "$missing" ]; then
    return 0
  fi
  echo "First start on this box: installing the libraries this assignment uses (a minute or two)..."
  # shellcheck disable=SC2086  # word-splitting $missing into separate specs is intended
  if pip3 install --user --quiet $missing; then
    return 0
  fi
  echo "Could not install:$missing. The box may have no internet access right now."
  echo "Tell your instructor; nothing in your own files is wrong."
  return 1
}

start_app() {
  if is_running; then
    echo "The Prompt Lab is already running on port ${PORT}."
    return 0
  fi
  ensure_packages || return 1
  PORT="$PORT" nohup python3 app.py >"$LOGFILE" 2>&1 &
  echo $! >"$PIDFILE"
  for _ in $(seq 1 30); do
    port_open && { echo "Prompt Lab running on port ${PORT}. Log: ${LOGFILE}"; return 0; }
    sleep 1
  done
  echo "The Prompt Lab did not start. The last lines of ${LOGFILE}:"
  tail -n 12 "$LOGFILE"
  return 1
}

stop_app() {
  if [ -f "$PIDFILE" ]; then
    kill "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null
    rm -f "$PIDFILE"
  fi
  pkill -f "python3 app.py" 2>/dev/null
  echo "Prompt Lab stopped."
}

case "${1:-start}" in
  start)   start_app ;;
  stop)    stop_app ;;
  restart) stop_app; sleep 1; start_app ;;
  status)  if is_running; then echo "Running on port ${PORT}."; else echo "Not running."; fi ;;
  prepare)
    # Install the libraries ahead of time, so the slow first-time install happens
    # while the student fills in .env, not while a later page waits on it.
    if ensure_packages; then
      echo "Setup is done. Fill in your .env, then go on."
    fi
    ;;
  *)       echo "usage: bash lab.sh start|restart|stop|status|prepare"; exit 2 ;;
esac
